filetype off

source ~/.vim/include/vundle_setup.vim

set nocompatible
set t_Co=256


nnoremap <F7> :tabp<CR>
nnoremap <F8> :tabn<CR>

"UI
source ~/.vim/include/ui.vim


"Python
source ~/.vim/include/python.vim


"Swapfiles
set backupdir=~/.vim/backup
set directory=~/.vim/backup

